os: osx
osx_image: xcode11.3
language: swift
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script: xcodebuild build test -workspace TopSwiftRepositories.xcworkspace -scheme "TopSwiftRepositories" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO
 
